name: sipeja_gemastik
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

flutter_launcher_icons:
  android: "sipeja_logo"
  # ios: true
  image_path: "assets/images/sipeja_logo_launcher.png"
  # min_sdk_android: 21

environment:
  sdk: ^3.8.1

dependencies:
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_map: ^8.2.1
  flutter_svg: ^2.2.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  http: ^1.5.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  latlong2: ^0.9.1
  permission_handler: ^12.0.1
  provider: ^6.1.5
  rename: ^3.1.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Aset untuk gambar tetap ada
  assets:
    - assets/images/

  # Aset untuk font dengan semua varian Poppins
  fonts:
    - family: Poppins
      fonts:
        # Thin
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        
        # ExtraLight
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic

        # Light
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic

        # Regular & Italic (Normal)
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic

        # Medium
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic

        # SemiBold
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic

        # Bold
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic

        # ExtraBold
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        # Black
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic